### ISSUE TITLE
load https://github.com/grate-driver/linux.git with your kernel?

### ISSUE THREAD

**Issue by hedmo** [zagto/tf300t-dtboot-kernel#1]
hi @zagto .

i just found your git and wonder if it is possible to load the kernel from https://github.com/grate-driver/linux.git?. ATM i am running kexec boot(dual boot with crombi-kk and gentoo). i have tried my hardest to get an up to date kernel to load on my gentoo partition with kexec multiboot but cannot.do you mind helping with this?. i have an unlocked tf700t and a tf300t

best regards .

**Comment by zagto** [comment]
yeah let me just check if I can still reproduce this stuff myself. Sadly it has always been quite hacky. Alternatively there is also a method to flash the new kernel to Recovery partition. It is not as nice with updating, initrd, etc, you los recovery, but should work 100%

**Comment by hedmo** [comment]
Thanks alot.i did not manage to flash the grate-driver kernel My self. I Always ended Up with failed to flash via adb. And IF i did try to load THE new kernel via kexec it just froze. My hope is to have a "quite" simple loader to load kernels on. THE Main issue i have ATM is that glibc DO not support THE old 3.10 kernel .

**Comment by zagto** [comment]
good news: I was able to get the kernel part working, with gcc 10 even, so no weird old compilers needed. Only thing missing for now is the kexec user space binary. I have an old build that only supports an older version of the dtb format, that still needs to be updated. But I was able to kexec both the android kernel and and 5.something I built some time ago.
For directly flashing the new kernel to the boot/recovery partitions: forget about that, they have size limits that don't fit typical linux disto initrds

**Comment by hedmo** [comment]
that is nice to hear.i know about the flash to boot/recovery partitions. i just does not work for tf300/700t  .when you are saying "both the android kernel and and 5.something" . are you talking about booting a 5.x kernel with your kexec boot?. if that is so do you mind provide me with with the kernel  and provide a howto switch from TF700t-AKBI v2.6.8 ( https://forum.xda-developers.com/t/kexecboot-on-the-tf700t-tf700t-akbi-v2-6-8.2387133/ ) to yours?

**Comment by zagto** [comment]
Yes i'm making a new build that includes the devices trees from your repo for all different models tf300t, tf700t etc and a guide how to install and reproduce

**Comment by zagto** [comment]
I created a release in my dtbootmenu repo (https://github.com/zagto/dtbootmenu), and added instructions in README.md.

With this version I was also able to boot the Grate kernel from your link, (although dock keyboard didn't work, probably unrelated)

Please let me know if it works for you, or if you have any questions

**Comment by zagto** [comment]
relevant when formatting the external disk: https://unix.stackexchange.com/questions/599371/how-do-i-mount-an-ext4-partition-created-on-a-recent-system-on-a-ten-year-old-2
(you may need to use `mke2fs -t ext4 -O '^metadata_csum,^64bit'` when formatting so the old kexec hardboot kernel can load from there)

alternatively you could also copy all the files (zImage, initrd, .dtbootmenu) of the linux distro to internal /sdcard/boot

**Comment by hedmo** [comment]
do you have any place where we can chat? matrix or telegram?

**Comment by zagto** [comment]
yes you can find me on Telegram under the same name as Github. I'll be offline for some time now, but we can chat later
